### ISSUE TITLE
Possible for 1281 and 1282?

### ISSUE THREAD

**Issue by Shad0wolf0** [AdamRaichu/suppress-OpenGL-1280#1]
I get spammed too much by this every second when I'm testing my modpack. It sometimes stops and sometimes it doesn't. You think you can do what you did to suppress 1281 and 1282?

**Comment by AdamRaichu** [comment]
I think I will add settings which add a toggle for suppressing each of the three errors.

**Comment by AdamRaichu** [comment]
Could you let me know which modpack you were testing when you saw errors 1281 and 1282? As I'm working on the config screen it would be nice to show a tooltip explaining known causes for each error.

**Comment by Shad0wolf0** [comment]
It's Shad0wolf0's Survival+ on Modrinth, but I'm in the process of updating it to 1.20.1 which is why I got those errors. I could send you a log if that works.

**Comment by AdamRaichu** [comment]
Sure, go ahead and post it here. I may also try testing to figure out which mods would be causing those errors.

**Comment by Shad0wolf0** [comment]
[log.log](https://github.com/AdamRaichu/suppress-OpenGL-1280/files/12374503/log.log)

**Comment by AdamRaichu** [comment]
Great, thanks. I'm going to delete your comment with the log because it seems to have some info in it that you might not want shared (directory structure, system information, MC username, etc.).

**Comment by AdamRaichu** [comment]
@KikuGie I noticed you have a fork of this repo for suppressing 1282. I just wanted to let you know in case you didn't already see it, that the main mod now suppresses 1282 by default, and also includes a config screen. Just FYI.

**Comment by kikugie** [comment]
Nice! I didn't plan on maintaining it, just made a quick change for myself to deal with litematica.
