### ISSUE TITLE
Add error to supress

### ISSUE THREAD

**Issue by nijahplays** [AdamRaichu/suppress-OpenGL-1280#3]
This error is non-fatal but it still spams logs

`[04:48:28] [Thread-79/INFO]: OpenGL debug message: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glCopyTexSubImage2D(invalid texture level 0)'
`
As seen in attached file 
[latest.log](https://github.com/AdamRaichu/suppress-OpenGL-1280/files/14494120/latest.log)

**Comment by AdamRaichu** [comment]
I personally did not have blur generate this error, but I'll add it anyway; there's no reason not to.
