### ISSUE TITLE
Fabric version works fine in 1.21

### ISSUE THREAD

**Issue by RacinanteOpus** [AdamRaichu/suppress-OpenGL-1280#6]
While I don't have Overwolf, I was getting the 1282 message spammed in my modded 1.21 Minecraft world.  Installed the 1.2.1 version and it works fine.  Thank you for this!

**Comment by AdamRaichu** [comment]
Thanks! I've kind of been behind the ball with updating my mods, but I'll update my config and push.

**Comment by AdamRaichu** [comment]
1.21 versions should now be live on both MR and CF.
