### ISSUE TITLE
1.21.3 support

### ISSUE THREAD

**Issue by nijahplays** [AdamRaichu/suppress-OpenGL-1280#9]
title

**Comment by vanvac** [comment]
it is compitable with 1.21.3 as there is no version incompatiablity in the fabricMod.json file
the newest jar should work with 1.21.3

**Comment by AdamRaichu** [comment]
So sorry I let this sit for a month. Sometime in the next couple days I'll make sure to update the mod pages to support 1.21.3 (and probably .4, mojang hasn't changed this code in a while).

**Comment by AdamRaichu** [comment]
As soon as CI finishes the update should be on MR (and will be on CF when approved). Please let me know if something doesn't work right as I didn't do any testing.
